-- Backend baseline for the existing public.urls schema.
-- user_id intentionally remains nullable: existing legacy rows have no owner.

alter table public.urls
  add column if not exists is_active boolean not null default true,
  add column if not exists updated_at timestamptz not null default now();

alter table public.urls
  alter column clicks_count type bigint
  using trunc(clicks_count)::bigint;

alter table public.urls
  add constraint urls_clicks_count_nonnegative
  check (clicks_count >= 0);

create index if not exists idx_urls_user_created
  on public.urls (user_id, created_at desc, id desc);

create index if not exists idx_urls_active_user_created
  on public.urls (user_id, created_at desc, id desc)
  where is_active = true;

create index if not exists idx_urls_no_clicks_user_created
  on public.urls (user_id, created_at desc, id desc)
  where clicks_count = 0;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = pg_catalog
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists urls_set_updated_at on public.urls;
create trigger urls_set_updated_at
before update on public.urls
for each row execute function public.set_updated_at();

create table if not exists public.link_click_events (
  id bigint generated by default as identity primary key,
  event_id uuid not null default extensions.gen_random_uuid(),
  link_id integer not null references public.urls(id) on delete cascade,
  clicked_at timestamptz not null default now(),
  referrer_host text,
  country_code text,
  visitor_hash text,
  constraint link_click_events_event_id_key unique (event_id)
);

create index if not exists idx_link_click_events_link_time
  on public.link_click_events (link_id, clicked_at desc, id desc);

create index if not exists idx_link_click_events_time
  on public.link_click_events (clicked_at desc, id desc);

alter table public.link_click_events enable row level security;
revoke all on public.link_click_events from anon;
revoke all on public.link_click_events from authenticated;
grant select on public.link_click_events to authenticated;

drop policy if exists "Users can read their own click events" on public.link_click_events;
create policy "Users can read their own click events"
on public.link_click_events
for select
to authenticated
using (
  exists (
    select 1
    from public.urls
    where urls.id = link_click_events.link_id
      and urls.user_id = (select auth.uid())::text
  )
);

create table if not exists public.analytics_coverage (
  singleton boolean primary key default true check (singleton = true),
  started_at timestamptz
);

alter table public.analytics_coverage enable row level security;
revoke all on public.analytics_coverage from anon;
revoke insert, update, delete, truncate on public.analytics_coverage from authenticated;
grant select on public.analytics_coverage to authenticated;

drop policy if exists "Authenticated users can read analytics coverage" on public.analytics_coverage;
create policy "Authenticated users can read analytics coverage"
on public.analytics_coverage
for select
to authenticated
using (true);

create or replace function public.resolve_active_link(slug_input text)
returns table (link_id integer, original_url text)
language sql
security definer
set search_path = pg_catalog, public
as $$
  select id, original_url
  from public.urls
  where slug = slug_input
    and is_active = true
  order by id
  limit 1;
$$;

revoke all on function public.resolve_active_link(text) from public;
grant execute on function public.resolve_active_link(text) to anon, authenticated, service_role;

create or replace function public.record_link_click(
  p_event_id uuid,
  p_link_id integer,
  p_clicked_at timestamptz,
  p_referrer_host text default null,
  p_country_code text default null,
  p_visitor_hash text default null
)
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  new_count bigint;
begin
  if not exists (select 1 from public.urls where id = p_link_id) then
    raise exception 'link_not_found' using errcode = 'P0002';
  end if;

  insert into public.link_click_events (
    event_id,
    link_id,
    clicked_at,
    referrer_host,
    country_code,
    visitor_hash
  ) values (
    p_event_id,
    p_link_id,
    coalesce(p_clicked_at, now()),
    p_referrer_host,
    p_country_code,
    p_visitor_hash
  ) on conflict (event_id) do nothing;

  if found then
    update public.urls
    set clicks_count = clicks_count + 1
    where id = p_link_id
    returning clicks_count into new_count;
  else
    select clicks_count into new_count
    from public.urls
    where id = p_link_id;
  end if;

  return new_count;
end;
$$;

revoke all on function public.record_link_click(uuid, integer, timestamptz, text, text, text) from public;
revoke all on function public.record_link_click(uuid, integer, timestamptz, text, text, text) from anon;
revoke all on function public.record_link_click(uuid, integer, timestamptz, text, text, text) from authenticated;
grant execute on function public.record_link_click(uuid, integer, timestamptz, text, text, text) to service_role;

alter function public.increment_clicks(text) set search_path = pg_catalog, public;
